# Omar Iván Flores Quijada
# Esteban Arocha Ortuño
# Enero - Mayo 2019
# ITESM

from tokens import *
SEM_CUBE = {
        INT: {
            INT:{
                PLUS : INT,
                MINUS : INT,
                MULT : INT,
                DIV : INT,
                EQU : BOOL,
                GREATER : BOOL,
                GREATER_EQ : BOOL,
                LESS : BOOL,
                LESS_EQ : BOOL,
                DIFF : BOOL,
                AND : ERROR,
                OR : ERROR,
                ASSIGN : INT
            },
            FLOAT:{
                PLUS : FLOAT,
                MINUS : FLOAT,
                MULT : FLOAT,
                DIV : FLOAT,
                EQU : BOOL,
                GREATER : BOOL,
                GREATER_EQ : BOOL,
                LESS : BOOL,
                LESS_EQ : BOOL,
                DIFF : BOOL,
                AND : ERROR,
                OR : ERROR,
                ASSIGN : INT
            },
            CHAR:{
                PLUS : ERROR,
                MINUS : ERROR,
                MULT : ERROR,
                DIV : ERROR,
                EQU : ERROR,
                GREATER : ERROR,
                GREATER_EQ : ERROR,
                LESS : ERROR,
                LESS_EQ : ERROR,
                DIFF : ERROR,
                AND : ERROR,
                OR : ERROR,
                ASSIGN : ERROR
            },
            BOOL:{
                PLUS : ERROR,
                MINUS : ERROR,
                MULT : ERROR,
                DIV : ERROR,
                EQU : ERROR,
                GREATER : ERROR,
                GREATER_EQ : ERROR,
                LESS : ERROR,
                LESS_EQ : ERROR,
                DIFF : ERROR,
                AND : ERROR,
                OR : ERROR,
                ASSIGN : ERROR
            }
        },
        FLOAT: {
            FLOAT:{
                PLUS : FLOAT,
                MINUS : FLOAT,
                MULT : FLOAT,
                DIV : FLOAT,
                EQU : BOOL,
                GREATER : BOOL,
                GREATER_EQ : BOOL,
                LESS : BOOL,
                LESS_EQ : BOOL,
                DIFF : BOOL,
                AND : ERROR,
                OR : ERROR,
                ASSIGN : FLOAT
            },
            INT:{
                PLUS : FLOAT,
                MINUS : FLOAT,
                MULT : FLOAT,
                DIV : FLOAT,
                EQU : BOOL,
                GREATER : BOOL,
                GREATER_EQ : BOOL,
                LESS : BOOL,
                LESS_EQ : BOOL,
                DIFF : BOOL,
                AND : ERROR,
                OR : ERROR,
                ASSIGN : FLOAT
            },
            CHAR:{
                PLUS : ERROR,
                MINUS : ERROR,
                MULT : ERROR,
                DIV : ERROR,
                EQU : ERROR,
                GREATER : ERROR,
                GREATER_EQ : ERROR,
                LESS : ERROR,
                LESS_EQ : ERROR,
                DIFF : ERROR,
                AND : ERROR,
                OR : ERROR,
                ASSIGN : ERROR
            },
            BOOL:{
                PLUS : ERROR,
                MINUS : ERROR,
                MULT : ERROR,
                DIV : ERROR,
                EQU : ERROR,
                GREATER : ERROR,
                GREATER_EQ : ERROR,
                LESS : ERROR,
                LESS_EQ : ERROR,
                DIFF : ERROR,
                AND : ERROR,
                OR : ERROR,
                ASSIGN : ERROR
            }
        },
        CHAR: {
            CHAR:{
                PLUS : ERROR,
                MINUS : ERROR,
                MULT : ERROR,
                DIV : ERROR,
                EQU : BOOL,
                GREATER : ERROR,
                GREATER_EQ : ERROR,
                LESS : ERROR,
                LESS_EQ : ERROR,
                DIFF : BOOL,
                AND : ERROR,
                OR : ERROR,
                ASSIGN : CHAR
            },
            INT:{
                PLUS : ERROR,
                MINUS : ERROR,
                MULT : ERROR,
                DIV : ERROR,
                EQU : ERROR,
                GREATER : ERROR,
                GREATER_EQ : ERROR,
                LESS : ERROR,
                LESS_EQ : ERROR,
                DIFF : ERROR,
                AND : ERROR,
                OR : ERROR,
                ASSIGN : ERROR
            },
            FLOAT:{
                PLUS : ERROR,
                MINUS : ERROR,
                MULT : ERROR,
                DIV : ERROR,
                EQU : ERROR,
                GREATER : ERROR,
                GREATER_EQ : ERROR,
                LESS : ERROR,
                LESS_EQ : ERROR,
                DIFF : ERROR,
                AND : ERROR,
                OR : ERROR,
                ASSIGN : ERROR
            },
            BOOL:{
                PLUS : ERROR,
                MINUS : ERROR,
                MULT : ERROR,
                DIV : ERROR,
                EQU : ERROR,
                GREATER : ERROR,
                GREATER_EQ : ERROR,
                LESS : ERROR,
                LESS_EQ : ERROR,
                DIFF : ERROR,
                AND : ERROR,
                OR : ERROR,
                ASSIGN : ERROR
            }
        },
        BOOL: {
            BOOL:{
                PLUS : ERROR,
                MINUS : ERROR,
                MULT : ERROR,
                DIV : ERROR,
                EQU : BOOL,
                GREATER : ERROR,
                GREATER_EQ : ERROR,
                LESS : ERROR,
                LESS_EQ : ERROR,
                DIFF : BOOL,
                AND : BOOL,
                OR : BOOL,
                ASSIGN : BOOL
            },
            INT:{
                PLUS : ERROR,
                MINUS : ERROR,
                MULT : ERROR,
                DIV : ERROR,
                EQU : ERROR,
                GREATER : ERROR,
                GREATER_EQ : ERROR,
                LESS : ERROR,
                LESS_EQ : ERROR,
                DIFF : ERROR,
                AND : ERROR,
                OR : ERROR,
                ASSIGN : ERROR
            },
            FLOAT:{
                PLUS : ERROR,
                MINUS : ERROR,
                MULT : ERROR,
                DIV : ERROR,
                EQU : ERROR,
                GREATER : ERROR,
                GREATER_EQ : ERROR,
                LESS : ERROR,
                LESS_EQ : ERROR,
                DIFF : ERROR,
                AND : ERROR,
                OR : ERROR,
                ASSIGN : ERROR
            },
            CHAR:{
                PLUS : ERROR,
                MINUS : ERROR,
                MULT : ERROR,
                DIV : ERROR,
                EQU : ERROR,
                GREATER : ERROR,
                GREATER_EQ : ERROR,
                LESS : ERROR,
                LESS_EQ : ERROR,
                DIFF : ERROR,
                AND : ERROR,
                OR : ERROR,
                ASSIGN : ERROR
            }
        }
    }
