VAR = "var"
CTE = "cte"
FUN = "fun"
ARR = "arr"
GLOBAL = "global"
TYPE = "tipo"
VARS = "vars"
PARAMS = 'params'
VOID = "void"
INT = 'int'
FLOAT = 'float'
CHAR = 'char'
BOOL = 'bool'
STRING = 'str'
PLUS = '+'
MINUS = '-'
MULT = '*'
DIV = '/'
EQU = '=='
GREATER = '>'
GREATER_EQ = '>='
LESS = '<'
LESS_EQ = '<='
DIFF = '!='
AND = '&&'
OR = '||'
ASSIGN = '='
ERROR = 'error'
PRINT = 'print'
PRINT_NEW_LINE = 'print_new_line'
READ = 'read'
RETURN = 'return'
GO_TO_F = 'go_to_f'
GO_TO = 'go_to'
START = 'start'
END_PROC = 'end_proc'
ERA = 'era'
GO_SUB = 'go_sub'
FILL_ARRAY = 'fill_array'
VER = 'ver'
PLUS_POINTER = "++"
ASSIGN_PARAM = '= param'
ASSIGN_ARRAY_PARAM = '= array_param'
INI_VAR = 'ini_var'